### ISSUE TITLE
[Features] - Data Requests and JSON parsing

### ISSUE THREAD

**Issue by namiwa** [AY1920S1-CS2113T-F10-1/main#74]
@andrewleow97 @kyawtsan99 @e0313687 @LongLeCE 
Feel free to comment below to request for more parsing/data processing features!

**Comment by LongLeCE** [comment]
Maybe create an interface for the module parser so that we can co-develop other features which depend on the module database

**Comment by LongLeCE** [comment]
Actually I think an abstract class would be better since we can import it instead of "implement" the interface

**Comment by andrewleow97** [comment]
May require ModuleList over TaskList, since a lot of module information is needed for our project, makes it easier to parse also without extending task.

Also might need CAPinfo class (extends moduleinfosummary?) which includes prereq, S/U, letter grade, completion status. for capcommand (Andrew's portion)

**Comment by namiwa** [comment]
@LongLeCE and @andrewleow97 , with reference to #81, I had implemented the basic detailed module information, using the list command as a temporary way to showcase the functionality of the module classes. Feel free to suggest any improvements to the base code!

**Comment by namiwa** [comment]
Update #86 fixed a big null pointer bug in the HashMap which was implemented in #82

**Comment by namiwa** [comment]
Closed as feature intended for v1.4 has been implemented.
